/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Article metadata as returned by the export endpoint. Identical to RankedArticle
 * but without the similarity `score` field and without the embedding vector.
 * 
 * @export
 * @interface ArticleExport
 */
export interface ArticleExport {
    /**
     * 
     * @type {string}
     * @memberof ArticleExport
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleExport
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleExport
     */
    summary?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticleExport
     */
    topics?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ArticleExport
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleExport
     */
    month?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleExport
     */
    startPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleExport
     */
    endPage?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleExport
     */
    pdfPath?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleExport
     */
    pdfPageOffset?: number;
}

/**
 * Check if a given object implements the ArticleExport interface.
 */
export function instanceOfArticleExport(value: object): value is ArticleExport {
    return true;
}

export function ArticleExportFromJSON(json: any): ArticleExport {
    return ArticleExportFromJSONTyped(json, false);
}

export function ArticleExportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleExport {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'topics': json['topics'] == null ? undefined : json['topics'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'startPage': json['startPage'] == null ? undefined : json['startPage'],
        'endPage': json['endPage'] == null ? undefined : json['endPage'],
        'pdfPath': json['pdfPath'] == null ? undefined : json['pdfPath'],
        'pdfPageOffset': json['pdfPageOffset'] == null ? undefined : json['pdfPageOffset'],
    };
}

  export function ArticleExportToJSON(json: any): ArticleExport {
      return ArticleExportToJSONTyped(json, false);
  }

  export function ArticleExportToJSONTyped(value?: ArticleExport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'topics': value['topics'],
        'year': value['year'],
        'month': value['month'],
        'startPage': value['startPage'],
        'endPage': value['endPage'],
        'pdfPath': value['pdfPath'],
        'pdfPageOffset': value['pdfPageOffset'],
    };
}

