/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface AutocompleteResponse
 */
export interface AutocompleteResponse {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteResponse
     */
    requestId?: string;
    /**
     * Suggested code to insert at the cursor.
     * @type {string}
     * @memberof AutocompleteResponse
     */
    completion?: string;
    /**
     * Whether the result was served from cache.
     * @type {boolean}
     * @memberof AutocompleteResponse
     */
    cached?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AutocompleteResponse
     */
    latencyMs?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof AutocompleteResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the AutocompleteResponse interface.
 */
export function instanceOfAutocompleteResponse(value: object): value is AutocompleteResponse {
    return true;
}

export function AutocompleteResponseFromJSON(json: any): AutocompleteResponse {
    return AutocompleteResponseFromJSONTyped(json, false);
}

export function AutocompleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'completion': json['completion'] == null ? undefined : json['completion'],
        'cached': json['cached'] == null ? undefined : json['cached'],
        'latencyMs': json['latencyMs'] == null ? undefined : json['latencyMs'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function AutocompleteResponseToJSON(json: any): AutocompleteResponse {
      return AutocompleteResponseToJSONTyped(json, false);
  }

  export function AutocompleteResponseToJSONTyped(value?: AutocompleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
        'completion': value['completion'],
        'cached': value['cached'],
        'latencyMs': value['latencyMs'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

