/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteRequest
 */
export interface AutocompleteRequest {
    /**
     * Code text before the cursor.
     * @type {string}
     * @memberof AutocompleteRequest
     */
    prefix: string;
    /**
     * Code text after the cursor (FIM context).
     * @type {string}
     * @memberof AutocompleteRequest
     */
    suffix?: string;
    /**
     * Programming language identifier (e.g. "typescript", "python").
     * @type {string}
     * @memberof AutocompleteRequest
     */
    language?: string;
}

/**
 * Check if a given object implements the AutocompleteRequest interface.
 */
export function instanceOfAutocompleteRequest(value: object): value is AutocompleteRequest {
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    return true;
}

export function AutocompleteRequestFromJSON(json: any): AutocompleteRequest {
    return AutocompleteRequestFromJSONTyped(json, false);
}

export function AutocompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prefix': json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'language': json['language'] == null ? undefined : json['language'],
    };
}

  export function AutocompleteRequestToJSON(json: any): AutocompleteRequest {
      return AutocompleteRequestToJSONTyped(json, false);
  }

  export function AutocompleteRequestToJSONTyped(value?: AutocompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prefix': value['prefix'],
        'suffix': value['suffix'],
        'language': value['language'],
    };
}

