/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHelp200ResponseEndpointsInnerParamsInner } from './GetHelp200ResponseEndpointsInnerParamsInner';
import {
    GetHelp200ResponseEndpointsInnerParamsInnerFromJSON,
    GetHelp200ResponseEndpointsInnerParamsInnerFromJSONTyped,
    GetHelp200ResponseEndpointsInnerParamsInnerToJSON,
    GetHelp200ResponseEndpointsInnerParamsInnerToJSONTyped,
} from './GetHelp200ResponseEndpointsInnerParamsInner';

/**
 * 
 * @export
 * @interface GetHelp200ResponseEndpointsInner
 */
export interface GetHelp200ResponseEndpointsInner {
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseEndpointsInner
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseEndpointsInner
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHelp200ResponseEndpointsInner
     */
    summary?: string;
    /**
     * 
     * @type {Array<GetHelp200ResponseEndpointsInnerParamsInner>}
     * @memberof GetHelp200ResponseEndpointsInner
     */
    params?: Array<GetHelp200ResponseEndpointsInnerParamsInner>;
}

/**
 * Check if a given object implements the GetHelp200ResponseEndpointsInner interface.
 */
export function instanceOfGetHelp200ResponseEndpointsInner(value: object): value is GetHelp200ResponseEndpointsInner {
    return true;
}

export function GetHelp200ResponseEndpointsInnerFromJSON(json: any): GetHelp200ResponseEndpointsInner {
    return GetHelp200ResponseEndpointsInnerFromJSONTyped(json, false);
}

export function GetHelp200ResponseEndpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200ResponseEndpointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'path': json['path'] == null ? undefined : json['path'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(GetHelp200ResponseEndpointsInnerParamsInnerFromJSON)),
    };
}

  export function GetHelp200ResponseEndpointsInnerToJSON(json: any): GetHelp200ResponseEndpointsInner {
      return GetHelp200ResponseEndpointsInnerToJSONTyped(json, false);
  }

  export function GetHelp200ResponseEndpointsInnerToJSONTyped(value?: GetHelp200ResponseEndpointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'path': value['path'],
        'summary': value['summary'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(GetHelp200ResponseEndpointsInnerParamsInnerToJSON)),
    };
}

