/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHelp200ResponseEndpointsInner } from './GetHelp200ResponseEndpointsInner';
import {
    GetHelp200ResponseEndpointsInnerFromJSON,
    GetHelp200ResponseEndpointsInnerFromJSONTyped,
    GetHelp200ResponseEndpointsInnerToJSON,
    GetHelp200ResponseEndpointsInnerToJSONTyped,
} from './GetHelp200ResponseEndpointsInner';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface GetHelp200Response
 */
export interface GetHelp200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHelp200Response
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof GetHelp200Response
     */
    endpointCount?: number;
    /**
     * 
     * @type {Array<GetHelp200ResponseEndpointsInner>}
     * @memberof GetHelp200Response
     */
    endpoints?: Array<GetHelp200ResponseEndpointsInner>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetHelp200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetHelp200Response interface.
 */
export function instanceOfGetHelp200Response(value: object): value is GetHelp200Response {
    return true;
}

export function GetHelp200ResponseFromJSON(json: any): GetHelp200Response {
    return GetHelp200ResponseFromJSONTyped(json, false);
}

export function GetHelp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHelp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'endpointCount': json['endpointCount'] == null ? undefined : json['endpointCount'],
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(GetHelp200ResponseEndpointsInnerFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetHelp200ResponseToJSON(json: any): GetHelp200Response {
      return GetHelp200ResponseToJSONTyped(json, false);
  }

  export function GetHelp200ResponseToJSONTyped(value?: GetHelp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'endpointCount': value['endpointCount'],
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(GetHelp200ResponseEndpointsInnerToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

