/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { GetInfoModels200ResponseModelsInner } from './GetInfoModels200ResponseModelsInner';
import {
    GetInfoModels200ResponseModelsInnerFromJSON,
    GetInfoModels200ResponseModelsInnerFromJSONTyped,
    GetInfoModels200ResponseModelsInnerToJSON,
    GetInfoModels200ResponseModelsInnerToJSONTyped,
} from './GetInfoModels200ResponseModelsInner';

/**
 * 
 * @export
 * @interface GetInfoModels200Response
 */
export interface GetInfoModels200Response {
    /**
     * Number of models available.
     * @type {number}
     * @memberof GetInfoModels200Response
     */
    count?: number;
    /**
     * The Ollama base URL queried.
     * @type {string}
     * @memberof GetInfoModels200Response
     */
    ollamaBaseUrl?: string;
    /**
     * 
     * @type {Array<GetInfoModels200ResponseModelsInner>}
     * @memberof GetInfoModels200Response
     */
    models?: Array<GetInfoModels200ResponseModelsInner>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetInfoModels200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetInfoModels200Response interface.
 */
export function instanceOfGetInfoModels200Response(value: object): value is GetInfoModels200Response {
    return true;
}

export function GetInfoModels200ResponseFromJSON(json: any): GetInfoModels200Response {
    return GetInfoModels200ResponseFromJSONTyped(json, false);
}

export function GetInfoModels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModels200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'ollamaBaseUrl': json['ollamaBaseUrl'] == null ? undefined : json['ollamaBaseUrl'],
        'models': json['models'] == null ? undefined : ((json['models'] as Array<any>).map(GetInfoModels200ResponseModelsInnerFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetInfoModels200ResponseToJSON(json: any): GetInfoModels200Response {
      return GetInfoModels200ResponseToJSONTyped(json, false);
  }

  export function GetInfoModels200ResponseToJSONTyped(value?: GetInfoModels200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'ollamaBaseUrl': value['ollamaBaseUrl'],
        'models': value['models'] == null ? undefined : ((value['models'] as Array<any>).map(GetInfoModels200ResponseModelsInnerToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

