/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetInfoModels502Response
 */
export interface GetInfoModels502Response {
    /**
     * 
     * @type {string}
     * @memberof GetInfoModels502Response
     */
    error?: string;
}

/**
 * Check if a given object implements the GetInfoModels502Response interface.
 */
export function instanceOfGetInfoModels502Response(value: object): value is GetInfoModels502Response {
    return true;
}

export function GetInfoModels502ResponseFromJSON(json: any): GetInfoModels502Response {
    return GetInfoModels502ResponseFromJSONTyped(json, false);
}

export function GetInfoModels502ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModels502Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function GetInfoModels502ResponseToJSON(json: any): GetInfoModels502Response {
      return GetInfoModels502ResponseToJSONTyped(json, false);
  }

  export function GetInfoModels502ResponseToJSONTyped(value?: GetInfoModels502Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

