/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetInfoModels200ResponseModelsInner
 */
export interface GetInfoModels200ResponseModelsInner {
    /**
     * 
     * @type {string}
     * @memberof GetInfoModels200ResponseModelsInner
     */
    name?: string;
    /**
     * Model file size in bytes.
     * @type {number}
     * @memberof GetInfoModels200ResponseModelsInner
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof GetInfoModels200ResponseModelsInner
     */
    digest?: string;
    /**
     * ISO 8601 timestamp of last modification.
     * @type {string}
     * @memberof GetInfoModels200ResponseModelsInner
     */
    modifiedAt?: string;
    /**
     * Ollama model metadata (family, parameter_size, quantization_level, etc.).
     * @type {object}
     * @memberof GetInfoModels200ResponseModelsInner
     */
    details?: object;
}

/**
 * Check if a given object implements the GetInfoModels200ResponseModelsInner interface.
 */
export function instanceOfGetInfoModels200ResponseModelsInner(value: object): value is GetInfoModels200ResponseModelsInner {
    return true;
}

export function GetInfoModels200ResponseModelsInnerFromJSON(json: any): GetInfoModels200ResponseModelsInner {
    return GetInfoModels200ResponseModelsInnerFromJSONTyped(json, false);
}

export function GetInfoModels200ResponseModelsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModels200ResponseModelsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'digest': json['digest'] == null ? undefined : json['digest'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : json['modifiedAt'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

  export function GetInfoModels200ResponseModelsInnerToJSON(json: any): GetInfoModels200ResponseModelsInner {
      return GetInfoModels200ResponseModelsInnerToJSONTyped(json, false);
  }

  export function GetInfoModels200ResponseModelsInnerToJSONTyped(value?: GetInfoModels200ResponseModelsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'size': value['size'],
        'digest': value['digest'],
        'modifiedAt': value['modifiedAt'],
        'details': value['details'],
    };
}

