/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { GetInfoModes200ResponseModesInner } from './GetInfoModes200ResponseModesInner';
import {
    GetInfoModes200ResponseModesInnerFromJSON,
    GetInfoModes200ResponseModesInnerFromJSONTyped,
    GetInfoModes200ResponseModesInnerToJSON,
    GetInfoModes200ResponseModesInnerToJSONTyped,
} from './GetInfoModes200ResponseModesInner';

/**
 * 
 * @export
 * @interface GetInfoModes200Response
 */
export interface GetInfoModes200Response {
    /**
     * Number of available modes.
     * @type {number}
     * @memberof GetInfoModes200Response
     */
    count?: number;
    /**
     * 
     * @type {Array<GetInfoModes200ResponseModesInner>}
     * @memberof GetInfoModes200Response
     */
    modes?: Array<GetInfoModes200ResponseModesInner>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof GetInfoModes200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the GetInfoModes200Response interface.
 */
export function instanceOfGetInfoModes200Response(value: object): value is GetInfoModes200Response {
    return true;
}

export function GetInfoModes200ResponseFromJSON(json: any): GetInfoModes200Response {
    return GetInfoModes200ResponseFromJSONTyped(json, false);
}

export function GetInfoModes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInfoModes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'modes': json['modes'] == null ? undefined : ((json['modes'] as Array<any>).map(GetInfoModes200ResponseModesInnerFromJSON)),
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function GetInfoModes200ResponseToJSON(json: any): GetInfoModes200Response {
      return GetInfoModes200ResponseToJSONTyped(json, false);
  }

  export function GetInfoModes200ResponseToJSONTyped(value?: GetInfoModes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'modes': value['modes'] == null ? undefined : ((value['modes'] as Array<any>).map(GetInfoModes200ResponseModesInnerToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

