/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageProcessorResponse
 */
export interface ImageProcessorResponse {
    /**
     * Base64-encoded PNG image produced by the processor.
     * @type {string}
     * @memberof ImageProcessorResponse
     */
    image: string;
    /**
     * Processing duration in milliseconds.
     * @type {number}
     * @memberof ImageProcessorResponse
     */
    durationMs: number;
    /**
     * Model identifier returned by the processor.
     * @type {string}
     * @memberof ImageProcessorResponse
     */
    model: string;
}

/**
 * Check if a given object implements the ImageProcessorResponse interface.
 */
export function instanceOfImageProcessorResponse(value: object): value is ImageProcessorResponse {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function ImageProcessorResponseFromJSON(json: any): ImageProcessorResponse {
    return ImageProcessorResponseFromJSONTyped(json, false);
}

export function ImageProcessorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageProcessorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'durationMs': json['duration_ms'],
        'model': json['model'],
    };
}

  export function ImageProcessorResponseToJSON(json: any): ImageProcessorResponse {
      return ImageProcessorResponseToJSONTyped(json, false);
  }

  export function ImageProcessorResponseToJSONTyped(value?: ImageProcessorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'duration_ms': value['durationMs'],
        'model': value['model'],
    };
}

