/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PdfEntry } from './PdfEntry';
import {
    PdfEntryFromJSON,
    PdfEntryFromJSONTyped,
    PdfEntryToJSON,
    PdfEntryToJSONTyped,
} from './PdfEntry';

/**
 * Provide either `pdfs` for incremental updates (specific files) or
 * `folder` for a full batch import. If both are provided, `pdfs` takes precedence.
 * 
 * @export
 * @interface ImportRequest
 */
export interface ImportRequest {
    /**
     * Array of specific PDF files to import.
     * @type {Array<PdfEntry>}
     * @memberof ImportRequest
     */
    pdfs?: Array<PdfEntry>;
    /**
     * Absolute path to a folder containing PDF files (scanned recursively).
     * All PDFs found under this path will be ingested.
     * 
     * @type {string}
     * @memberof ImportRequest
     */
    folder?: string;
}

/**
 * Check if a given object implements the ImportRequest interface.
 */
export function instanceOfImportRequest(value: object): value is ImportRequest {
    return true;
}

export function ImportRequestFromJSON(json: any): ImportRequest {
    return ImportRequestFromJSONTyped(json, false);
}

export function ImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pdfs': json['pdfs'] == null ? undefined : ((json['pdfs'] as Array<any>).map(PdfEntryFromJSON)),
        'folder': json['folder'] == null ? undefined : json['folder'],
    };
}

  export function ImportRequestToJSON(json: any): ImportRequest {
      return ImportRequestToJSONTyped(json, false);
  }

  export function ImportRequestToJSONTyped(value?: ImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pdfs': value['pdfs'] == null ? undefined : ((value['pdfs'] as Array<any>).map(PdfEntryToJSON)),
        'folder': value['folder'],
    };
}

