/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportResult
 */
export interface ImportResult {
    /**
     * Number of articles successfully imported.
     * @type {number}
     * @memberof ImportResult
     */
    imported?: number;
    /**
     * Number of PDFs skipped due to errors.
     * @type {number}
     * @memberof ImportResult
     */
    skipped?: number;
    /**
     * Error messages for any PDFs that failed to process.
     * @type {Array<string>}
     * @memberof ImportResult
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the ImportResult interface.
 */
export function instanceOfImportResult(value: object): value is ImportResult {
    return true;
}

export function ImportResultFromJSON(json: any): ImportResult {
    return ImportResultFromJSONTyped(json, false);
}

export function ImportResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportResult {
    if (json == null) {
        return json;
    }
    return {
        
        'imported': json['imported'] == null ? undefined : json['imported'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

  export function ImportResultToJSON(json: any): ImportResult {
      return ImportResultToJSONTyped(json, false);
  }

  export function ImportResultToJSONTyped(value?: ImportResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imported': value['imported'],
        'skipped': value['skipped'],
        'errors': value['errors'],
    };
}

