/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LibraryInfo
 */
export interface LibraryInfo {
    /**
     * Library identifier.
     * @type {string}
     * @memberof LibraryInfo
     */
    id?: string;
    /**
     * Human-readable display name.
     * @type {string}
     * @memberof LibraryInfo
     */
    name?: string;
    /**
     * Number of articles currently indexed.
     * @type {number}
     * @memberof LibraryInfo
     */
    articleCount?: number;
    /**
     * ISO 8601 timestamp of the most recent import run.
     * @type {Date}
     * @memberof LibraryInfo
     */
    lastImport?: Date;
}

/**
 * Check if a given object implements the LibraryInfo interface.
 */
export function instanceOfLibraryInfo(value: object): value is LibraryInfo {
    return true;
}

export function LibraryInfoFromJSON(json: any): LibraryInfo {
    return LibraryInfoFromJSONTyped(json, false);
}

export function LibraryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibraryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'articleCount': json['articleCount'] == null ? undefined : json['articleCount'],
        'lastImport': json['lastImport'] == null ? undefined : (new Date(json['lastImport'])),
    };
}

  export function LibraryInfoToJSON(json: any): LibraryInfo {
      return LibraryInfoToJSONTyped(json, false);
  }

  export function LibraryInfoToJSONTyped(value?: LibraryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'articleCount': value['articleCount'],
        'lastImport': value['lastImport'] == null ? undefined : ((value['lastImport']).toISOString()),
    };
}

