/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LintResponseFindingsInner
 */
export interface LintResponseFindingsInner {
    /**
     * 
     * @type {string}
     * @memberof LintResponseFindingsInner
     */
    severity?: LintResponseFindingsInnerSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof LintResponseFindingsInner
     */
    rule?: string;
    /**
     * 
     * @type {number}
     * @memberof LintResponseFindingsInner
     */
    line?: number;
    /**
     * 
     * @type {string}
     * @memberof LintResponseFindingsInner
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof LintResponseFindingsInner
     */
    suggestion?: string;
}


/**
 * @export
 */
export const LintResponseFindingsInnerSeverityEnum = {
    Error: 'error',
    Warning: 'warning',
    Info: 'info'
} as const;
export type LintResponseFindingsInnerSeverityEnum = typeof LintResponseFindingsInnerSeverityEnum[keyof typeof LintResponseFindingsInnerSeverityEnum];


/**
 * Check if a given object implements the LintResponseFindingsInner interface.
 */
export function instanceOfLintResponseFindingsInner(value: object): value is LintResponseFindingsInner {
    return true;
}

export function LintResponseFindingsInnerFromJSON(json: any): LintResponseFindingsInner {
    return LintResponseFindingsInnerFromJSONTyped(json, false);
}

export function LintResponseFindingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LintResponseFindingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'severity': json['severity'] == null ? undefined : json['severity'],
        'rule': json['rule'] == null ? undefined : json['rule'],
        'line': json['line'] == null ? undefined : json['line'],
        'message': json['message'] == null ? undefined : json['message'],
        'suggestion': json['suggestion'] == null ? undefined : json['suggestion'],
    };
}

  export function LintResponseFindingsInnerToJSON(json: any): LintResponseFindingsInner {
      return LintResponseFindingsInnerToJSONTyped(json, false);
  }

  export function LintResponseFindingsInnerToJSONTyped(value?: LintResponseFindingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'severity': value['severity'],
        'rule': value['rule'],
        'line': value['line'],
        'message': value['message'],
        'suggestion': value['suggestion'],
    };
}

