/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LintConventionsRequest
 */
export interface LintConventionsRequest {
    /**
     * Source code to lint.
     * @type {string}
     * @memberof LintConventionsRequest
     */
    code: string;
    /**
     * Programming language identifier.
     * @type {string}
     * @memberof LintConventionsRequest
     */
    language?: string;
    /**
     * Optional source file name/path for context.
     * @type {string}
     * @memberof LintConventionsRequest
     */
    filename?: string;
    /**
     * Whether to include the optional LLM enrichment pass.
     * @type {boolean}
     * @memberof LintConventionsRequest
     */
    includeLlm?: boolean;
    /**
     * Override the model used for LLM enrichment.
     * @type {string}
     * @memberof LintConventionsRequest
     */
    model?: string;
    /**
     * Maximum number of findings returned.
     * @type {number}
     * @memberof LintConventionsRequest
     */
    maxFindings?: number;
}

/**
 * Check if a given object implements the LintConventionsRequest interface.
 */
export function instanceOfLintConventionsRequest(value: object): value is LintConventionsRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function LintConventionsRequestFromJSON(json: any): LintConventionsRequest {
    return LintConventionsRequestFromJSONTyped(json, false);
}

export function LintConventionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LintConventionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'language': json['language'] == null ? undefined : json['language'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'includeLlm': json['includeLlm'] == null ? undefined : json['includeLlm'],
        'model': json['model'] == null ? undefined : json['model'],
        'maxFindings': json['maxFindings'] == null ? undefined : json['maxFindings'],
    };
}

  export function LintConventionsRequestToJSON(json: any): LintConventionsRequest {
      return LintConventionsRequestToJSONTyped(json, false);
  }

  export function LintConventionsRequestToJSONTyped(value?: LintConventionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'language': value['language'],
        'filename': value['filename'],
        'includeLlm': value['includeLlm'],
        'model': value['model'],
        'maxFindings': value['maxFindings'],
    };
}

