/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LintResponseSummary
 */
export interface LintResponseSummary {
    /**
     * 
     * @type {number}
     * @memberof LintResponseSummary
     */
    errors?: number;
    /**
     * 
     * @type {number}
     * @memberof LintResponseSummary
     */
    warnings?: number;
    /**
     * 
     * @type {number}
     * @memberof LintResponseSummary
     */
    infos?: number;
    /**
     * 
     * @type {number}
     * @memberof LintResponseSummary
     */
    deterministicCount?: number;
    /**
     * 
     * @type {number}
     * @memberof LintResponseSummary
     */
    llmCount?: number;
}

/**
 * Check if a given object implements the LintResponseSummary interface.
 */
export function instanceOfLintResponseSummary(value: object): value is LintResponseSummary {
    return true;
}

export function LintResponseSummaryFromJSON(json: any): LintResponseSummary {
    return LintResponseSummaryFromJSONTyped(json, false);
}

export function LintResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LintResponseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : json['errors'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
        'infos': json['infos'] == null ? undefined : json['infos'],
        'deterministicCount': json['deterministicCount'] == null ? undefined : json['deterministicCount'],
        'llmCount': json['llmCount'] == null ? undefined : json['llmCount'],
    };
}

  export function LintResponseSummaryToJSON(json: any): LintResponseSummary {
      return LintResponseSummaryToJSONTyped(json, false);
  }

  export function LintResponseSummaryToJSONTyped(value?: LintResponseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'warnings': value['warnings'],
        'infos': value['infos'],
        'deterministicCount': value['deterministicCount'],
        'llmCount': value['llmCount'],
    };
}

