/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LintResponseFindingsInner } from './LintResponseFindingsInner';
import {
    LintResponseFindingsInnerFromJSON,
    LintResponseFindingsInnerFromJSONTyped,
    LintResponseFindingsInnerToJSON,
    LintResponseFindingsInnerToJSONTyped,
} from './LintResponseFindingsInner';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { LintResponseSummary } from './LintResponseSummary';
import {
    LintResponseSummaryFromJSON,
    LintResponseSummaryFromJSONTyped,
    LintResponseSummaryToJSON,
    LintResponseSummaryToJSONTyped,
} from './LintResponseSummary';

/**
 * 
 * @export
 * @interface LintResponse
 */
export interface LintResponse {
    /**
     * 
     * @type {string}
     * @memberof LintResponse
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof LintResponse
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof LintResponse
     */
    filePath?: string;
    /**
     * 
     * @type {LintResponseSummary}
     * @memberof LintResponse
     */
    summary?: LintResponseSummary;
    /**
     * 
     * @type {Array<LintResponseFindingsInner>}
     * @memberof LintResponse
     */
    findings?: Array<LintResponseFindingsInner>;
    /**
     * 
     * @type {string}
     * @memberof LintResponse
     */
    llmModelUsed?: string;
    /**
     * 
     * @type {number}
     * @memberof LintResponse
     */
    latencyMs?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof LintResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the LintResponse interface.
 */
export function instanceOfLintResponse(value: object): value is LintResponse {
    return true;
}

export function LintResponseFromJSON(json: any): LintResponse {
    return LintResponseFromJSONTyped(json, false);
}

export function LintResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LintResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'language': json['language'] == null ? undefined : json['language'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'summary': json['summary'] == null ? undefined : LintResponseSummaryFromJSON(json['summary']),
        'findings': json['findings'] == null ? undefined : ((json['findings'] as Array<any>).map(LintResponseFindingsInnerFromJSON)),
        'llmModelUsed': json['llmModelUsed'] == null ? undefined : json['llmModelUsed'],
        'latencyMs': json['latencyMs'] == null ? undefined : json['latencyMs'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function LintResponseToJSON(json: any): LintResponse {
      return LintResponseToJSONTyped(json, false);
  }

  export function LintResponseToJSONTyped(value?: LintResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
        'language': value['language'],
        'filePath': value['filePath'],
        'summary': LintResponseSummaryToJSON(value['summary']),
        'findings': value['findings'] == null ? undefined : ((value['findings'] as Array<any>).map(LintResponseFindingsInnerToJSON)),
        'llmModelUsed': value['llmModelUsed'],
        'latencyMs': value['latencyMs'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

