/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageReviewRequest
 */
export interface PageReviewRequest {
    /**
     * Full source file content to review.
     * @type {string}
     * @memberof PageReviewRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PageReviewRequest
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof PageReviewRequest
     */
    filename?: string;
    /**
     * Optional sentence describing the project for context.
     * @type {string}
     * @memberof PageReviewRequest
     */
    projectContext?: string;
}

/**
 * Check if a given object implements the PageReviewRequest interface.
 */
export function instanceOfPageReviewRequest(value: object): value is PageReviewRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function PageReviewRequestFromJSON(json: any): PageReviewRequest {
    return PageReviewRequestFromJSONTyped(json, false);
}

export function PageReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'language': json['language'] == null ? undefined : json['language'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'projectContext': json['projectContext'] == null ? undefined : json['projectContext'],
    };
}

  export function PageReviewRequestToJSON(json: any): PageReviewRequest {
      return PageReviewRequestToJSONTyped(json, false);
  }

  export function PageReviewRequestToJSONTyped(value?: PageReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'language': value['language'],
        'filename': value['filename'],
        'projectContext': value['projectContext'],
    };
}

