/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PdfEntry
 */
export interface PdfEntry {
    /**
     * Absolute path to the PDF file on disk.
     * @type {string}
     * @memberof PdfEntry
     */
    path: string;
    /**
     * Publication year. If omitted, the pipeline attempts to infer it
     * from the file path (e.g. .../2026/04.pdf -> 2026).
     * 
     * @type {number}
     * @memberof PdfEntry
     */
    year?: number;
    /**
     * Publication month as a full English name. If omitted, the pipeline
     * attempts to infer it from the file path.
     * 
     * @type {string}
     * @memberof PdfEntry
     */
    month?: string;
}

/**
 * Check if a given object implements the PdfEntry interface.
 */
export function instanceOfPdfEntry(value: object): value is PdfEntry {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function PdfEntryFromJSON(json: any): PdfEntry {
    return PdfEntryFromJSONTyped(json, false);
}

export function PdfEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PdfEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
    };
}

  export function PdfEntryToJSON(json: any): PdfEntry {
      return PdfEntryToJSONTyped(json, false);
  }

  export function PdfEntryToJSONTyped(value?: PdfEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'year': value['year'],
        'month': value['month'],
    };
}

