/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RankedArticle
 */
export interface RankedArticle {
    /**
     * Cosine similarity score between the query embedding and the article embedding.
     * @type {number}
     * @memberof RankedArticle
     */
    score?: number;
    /**
     * Unique article identifier.
     * @type {string}
     * @memberof RankedArticle
     */
    id?: string;
    /**
     * Article headline.
     * @type {string}
     * @memberof RankedArticle
     */
    title?: string;
    /**
     * LLM-generated 2-4 sentence summary.
     * @type {string}
     * @memberof RankedArticle
     */
    summary?: string;
    /**
     * LLM-generated topic tags.
     * @type {Array<string>}
     * @memberof RankedArticle
     */
    topics?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RankedArticle
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof RankedArticle
     */
    month?: string;
    /**
     * First printed page number of the article.
     * @type {number}
     * @memberof RankedArticle
     */
    startPage?: number;
    /**
     * Last printed page number of the article (may be absent for single-page items).
     * @type {number}
     * @memberof RankedArticle
     */
    endPage?: number;
    /**
     * Absolute path to the PDF on disk. Use with `startPage` to open directly.
     * @type {string}
     * @memberof RankedArticle
     */
    pdfPath?: string;
    /**
     * Offset between the printed page number and the 0-based PDF page index.
     * Use when cover pages or ads shift the internal page count.
     * 
     * @type {number}
     * @memberof RankedArticle
     */
    pdfPageOffset?: number;
}

/**
 * Check if a given object implements the RankedArticle interface.
 */
export function instanceOfRankedArticle(value: object): value is RankedArticle {
    return true;
}

export function RankedArticleFromJSON(json: any): RankedArticle {
    return RankedArticleFromJSONTyped(json, false);
}

export function RankedArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankedArticle {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'topics': json['topics'] == null ? undefined : json['topics'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'startPage': json['startPage'] == null ? undefined : json['startPage'],
        'endPage': json['endPage'] == null ? undefined : json['endPage'],
        'pdfPath': json['pdfPath'] == null ? undefined : json['pdfPath'],
        'pdfPageOffset': json['pdfPageOffset'] == null ? undefined : json['pdfPageOffset'],
    };
}

  export function RankedArticleToJSON(json: any): RankedArticle {
      return RankedArticleToJSONTyped(json, false);
  }

  export function RankedArticleToJSONTyped(value?: RankedArticle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'topics': value['topics'],
        'year': value['year'],
        'month': value['month'],
        'startPage': value['startPage'],
        'endPage': value['endPage'],
        'pdfPath': value['pdfPath'],
        'pdfPageOffset': value['pdfPageOffset'],
    };
}

