/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional operational metadata attached to successful responses.
 * @export
 * @interface ResponseMeta
 */
export interface ResponseMeta {
    /**
     * Wall-clock request duration in milliseconds.
     * @type {number}
     * @memberof ResponseMeta
     */
    durationMs?: number;
    /**
     * ISO 8601 timestamp when processing started.
     * @type {string}
     * @memberof ResponseMeta
     */
    startedAt?: string;
    /**
     * Prompt token count when provided by the model backend.
     * @type {number}
     * @memberof ResponseMeta
     */
    promptTokens?: number;
    /**
     * Completion token count when provided by the model backend.
     * @type {number}
     * @memberof ResponseMeta
     */
    completionTokens?: number;
    /**
     * Prompt + completion token count when both are available.
     * @type {number}
     * @memberof ResponseMeta
     */
    totalTokens?: number;
    /**
     * Single model identifier when only one model was used.
     * @type {string}
     * @memberof ResponseMeta
     */
    model?: string;
    /**
     * Model identifiers used during multi-step or routed execution.
     * @type {Array<string>}
     * @memberof ResponseMeta
     */
    models?: Array<string>;
    /**
     * Effective profile used by the operation when applicable.
     * @type {string}
     * @memberof ResponseMeta
     */
    profile?: string;
    /**
     * Number of reasoning or orchestration steps executed.
     * @type {number}
     * @memberof ResponseMeta
     */
    steps?: number;
    /**
     * Number of tool calls executed.
     * @type {number}
     * @memberof ResponseMeta
     */
    toolCalls?: number;
    /**
     * Final context length in characters when available.
     * @type {number}
     * @memberof ResponseMeta
     */
    contextLength?: number;
    /**
     * Request correlation identifier when available.
     * @type {string}
     * @memberof ResponseMeta
     */
    requestId?: string;
    /**
     * Whether memory retrieval returned non-empty context.
     * @type {boolean}
     * @memberof ResponseMeta
     */
    memoryUsed?: boolean;
}

/**
 * Check if a given object implements the ResponseMeta interface.
 */
export function instanceOfResponseMeta(value: object): value is ResponseMeta {
    return true;
}

export function ResponseMetaFromJSON(json: any): ResponseMeta {
    return ResponseMetaFromJSONTyped(json, false);
}

export function ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'promptTokens': json['promptTokens'] == null ? undefined : json['promptTokens'],
        'completionTokens': json['completionTokens'] == null ? undefined : json['completionTokens'],
        'totalTokens': json['totalTokens'] == null ? undefined : json['totalTokens'],
        'model': json['model'] == null ? undefined : json['model'],
        'models': json['models'] == null ? undefined : json['models'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'toolCalls': json['toolCalls'] == null ? undefined : json['toolCalls'],
        'contextLength': json['contextLength'] == null ? undefined : json['contextLength'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'memoryUsed': json['memoryUsed'] == null ? undefined : json['memoryUsed'],
    };
}

  export function ResponseMetaToJSON(json: any): ResponseMeta {
      return ResponseMetaToJSONTyped(json, false);
  }

  export function ResponseMetaToJSONTyped(value?: ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'durationMs': value['durationMs'],
        'startedAt': value['startedAt'],
        'promptTokens': value['promptTokens'],
        'completionTokens': value['completionTokens'],
        'totalTokens': value['totalTokens'],
        'model': value['model'],
        'models': value['models'],
        'profile': value['profile'],
        'steps': value['steps'],
        'toolCalls': value['toolCalls'],
        'contextLength': value['contextLength'],
        'requestId': value['requestId'],
        'memoryUsed': value['memoryUsed'],
    };
}

