/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunRequest
 */
export interface RunRequest {
    /**
     * Natural-language description of what the agent should do.
     * @type {string}
     * @memberof RunRequest
     */
    task: string;
    /**
     * When `true`, unlocks the `write_file`, `scaffold_project`, and `document_ingest` tools.
     * Default `false`.
     * 
     * @type {boolean}
     * @memberof RunRequest
     */
    allowWrite?: boolean;
    /**
     * Force a specific model profile, bypassing automatic routing.
     * If omitted, the router selects a profile based on the task text.
     * 
     * @type {string}
     * @memberof RunRequest
     */
    profile?: RunRequestProfileEnum;
}


/**
 * @export
 */
export const RunRequestProfileEnum = {
    Fast: 'fast',
    Reasoning: 'reasoning',
    Code: 'code',
    Default: 'default'
} as const;
export type RunRequestProfileEnum = typeof RunRequestProfileEnum[keyof typeof RunRequestProfileEnum];


/**
 * Check if a given object implements the RunRequest interface.
 */
export function instanceOfRunRequest(value: object): value is RunRequest {
    if (!('task' in value) || value['task'] === undefined) return false;
    return true;
}

export function RunRequestFromJSON(json: any): RunRequest {
    return RunRequestFromJSONTyped(json, false);
}

export function RunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'],
        'allowWrite': json['allowWrite'] == null ? undefined : json['allowWrite'],
        'profile': json['profile'] == null ? undefined : json['profile'],
    };
}

  export function RunRequestToJSON(json: any): RunRequest {
      return RunRequestToJSONTyped(json, false);
  }

  export function RunRequestToJSONTyped(value?: RunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': value['task'],
        'allowWrite': value['allowWrite'],
        'profile': value['profile'],
    };
}

