/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchRequestFilters } from './SearchRequestFilters';
import {
    SearchRequestFiltersFromJSON,
    SearchRequestFiltersFromJSONTyped,
    SearchRequestFiltersToJSON,
    SearchRequestFiltersToJSONTyped,
} from './SearchRequestFilters';

/**
 * 
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
    /**
     * Natural-language search query. Will be embedded using the configured embedding model.
     * @type {string}
     * @memberof SearchRequest
     */
    query: string;
    /**
     * Number of top-ranked articles to return.
     * @type {number}
     * @memberof SearchRequest
     */
    topK?: number;
    /**
     * 
     * @type {SearchRequestFilters}
     * @memberof SearchRequest
     */
    filters?: SearchRequestFilters;
}

/**
 * Check if a given object implements the SearchRequest interface.
 */
export function instanceOfSearchRequest(value: object): value is SearchRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SearchRequestFromJSON(json: any): SearchRequest {
    return SearchRequestFromJSONTyped(json, false);
}

export function SearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'topK': json['topK'] == null ? undefined : json['topK'],
        'filters': json['filters'] == null ? undefined : SearchRequestFiltersFromJSON(json['filters']),
    };
}

  export function SearchRequestToJSON(json: any): SearchRequest {
      return SearchRequestToJSONTyped(json, false);
  }

  export function SearchRequestToJSONTyped(value?: SearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'topK': value['topK'],
        'filters': SearchRequestFiltersToJSON(value['filters']),
    };
}

