/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional metadata filters applied before or during the ANN search.
 * @export
 * @interface SearchRequestFilters
 */
export interface SearchRequestFilters {
    /**
     * Restrict results to a specific publication year.
     * @type {number}
     * @memberof SearchRequestFilters
     */
    year?: number;
    /**
     * Restrict results to a specific publication month (full English name).
     * @type {string}
     * @memberof SearchRequestFilters
     */
    month?: string;
}

/**
 * Check if a given object implements the SearchRequestFilters interface.
 */
export function instanceOfSearchRequestFilters(value: object): value is SearchRequestFilters {
    return true;
}

export function SearchRequestFiltersFromJSON(json: any): SearchRequestFilters {
    return SearchRequestFiltersFromJSONTyped(json, false);
}

export function SearchRequestFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequestFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
    };
}

  export function SearchRequestFiltersToJSON(json: any): SearchRequestFilters {
      return SearchRequestFiltersToJSONTyped(json, false);
  }

  export function SearchRequestFiltersToJSONTyped(value?: SearchRequestFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
    };
}

