/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Workflow step input definition.
 * @export
 * @interface StepDefinition
 */
export interface StepDefinition {
    /**
     * Task text to run for this workflow step.
     * @type {string}
     * @memberof StepDefinition
     */
    task: string;
}

/**
 * Check if a given object implements the StepDefinition interface.
 */
export function instanceOfStepDefinition(value: object): value is StepDefinition {
    if (!('task' in value) || value['task'] === undefined) return false;
    return true;
}

export function StepDefinitionFromJSON(json: any): StepDefinition {
    return StepDefinitionFromJSONTyped(json, false);
}

export function StepDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'],
    };
}

  export function StepDefinitionToJSON(json: any): StepDefinition {
      return StepDefinitionToJSONTyped(json, false);
  }

  export function StepDefinitionToJSONTyped(value?: StepDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': value['task'],
    };
}

