/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwarmSubtaskResult
 */
export interface SwarmSubtaskResult {
    /**
     * Subtask identifier.
     * @type {string}
     * @memberof SwarmSubtaskResult
     */
    id?: string;
    /**
     * What this subtask was asked to do.
     * @type {string}
     * @memberof SwarmSubtaskResult
     */
    description?: string;
    /**
     * Model profile used for this subtask.
     * @type {string}
     * @memberof SwarmSubtaskResult
     */
    profile?: string;
    /**
     * Whether the subtask completed without error.
     * @type {boolean}
     * @memberof SwarmSubtaskResult
     */
    success?: boolean;
    /**
     * The subtask agent's final answer.
     * @type {string}
     * @memberof SwarmSubtaskResult
     */
    answer?: string;
    /**
     * Wall-clock execution time in milliseconds.
     * @type {number}
     * @memberof SwarmSubtaskResult
     */
    durationMs?: number;
    /**
     * Error message (only present when `success` is `false`).
     * @type {string}
     * @memberof SwarmSubtaskResult
     */
    error?: string;
}

/**
 * Check if a given object implements the SwarmSubtaskResult interface.
 */
export function instanceOfSwarmSubtaskResult(value: object): value is SwarmSubtaskResult {
    return true;
}

export function SwarmSubtaskResultFromJSON(json: any): SwarmSubtaskResult {
    return SwarmSubtaskResultFromJSONTyped(json, false);
}

export function SwarmSubtaskResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwarmSubtaskResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'success': json['success'] == null ? undefined : json['success'],
        'answer': json['answer'] == null ? undefined : json['answer'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function SwarmSubtaskResultToJSON(json: any): SwarmSubtaskResult {
      return SwarmSubtaskResultToJSONTyped(json, false);
  }

  export function SwarmSubtaskResultToJSONTyped(value?: SwarmSubtaskResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'profile': value['profile'],
        'success': value['success'],
        'answer': value['answer'],
        'durationMs': value['durationMs'],
        'error': value['error'],
    };
}

