/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SwarmResponseDecomposition } from './SwarmResponseDecomposition';
import {
    SwarmResponseDecompositionFromJSON,
    SwarmResponseDecompositionFromJSONTyped,
    SwarmResponseDecompositionToJSON,
    SwarmResponseDecompositionToJSONTyped,
} from './SwarmResponseDecomposition';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { SwarmSubtaskResult } from './SwarmSubtaskResult';
import {
    SwarmSubtaskResultFromJSON,
    SwarmSubtaskResultFromJSONTyped,
    SwarmSubtaskResultToJSON,
    SwarmSubtaskResultToJSONTyped,
} from './SwarmSubtaskResult';

/**
 * 
 * @export
 * @interface SwarmResponse
 */
export interface SwarmResponse {
    /**
     * The synthesised final answer.
     * @type {string}
     * @memberof SwarmResponse
     */
    answer?: string;
    /**
     * Individual results for each subtask.
     * @type {Array<SwarmSubtaskResult>}
     * @memberof SwarmResponse
     */
    subtaskResults?: Array<SwarmSubtaskResult>;
    /**
     * 
     * @type {SwarmResponseDecomposition}
     * @memberof SwarmResponse
     */
    decomposition?: SwarmResponseDecomposition;
    /**
     * Total wall-clock duration of the entire swarm run.
     * @type {number}
     * @memberof SwarmResponse
     */
    totalDurationMs?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof SwarmResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the SwarmResponse interface.
 */
export function instanceOfSwarmResponse(value: object): value is SwarmResponse {
    return true;
}

export function SwarmResponseFromJSON(json: any): SwarmResponse {
    return SwarmResponseFromJSONTyped(json, false);
}

export function SwarmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwarmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'] == null ? undefined : json['answer'],
        'subtaskResults': json['subtaskResults'] == null ? undefined : ((json['subtaskResults'] as Array<any>).map(SwarmSubtaskResultFromJSON)),
        'decomposition': json['decomposition'] == null ? undefined : SwarmResponseDecompositionFromJSON(json['decomposition']),
        'totalDurationMs': json['totalDurationMs'] == null ? undefined : json['totalDurationMs'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function SwarmResponseToJSON(json: any): SwarmResponse {
      return SwarmResponseToJSONTyped(json, false);
  }

  export function SwarmResponseToJSONTyped(value?: SwarmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'subtaskResults': value['subtaskResults'] == null ? undefined : ((value['subtaskResults'] as Array<any>).map(SwarmSubtaskResultToJSON)),
        'decomposition': SwarmResponseDecompositionToJSON(value['decomposition']),
        'totalDurationMs': value['totalDurationMs'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

