/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwarmResponseDecomposition
 */
export interface SwarmResponseDecomposition {
    /**
     * Decomposer's rationale for the subtask split.
     * @type {string}
     * @memberof SwarmResponseDecomposition
     */
    reasoning?: string;
    /**
     * Number of subtasks in the decomposition.
     * @type {number}
     * @memberof SwarmResponseDecomposition
     */
    subtaskCount?: number;
}

/**
 * Check if a given object implements the SwarmResponseDecomposition interface.
 */
export function instanceOfSwarmResponseDecomposition(value: object): value is SwarmResponseDecomposition {
    return true;
}

export function SwarmResponseDecompositionFromJSON(json: any): SwarmResponseDecomposition {
    return SwarmResponseDecompositionFromJSONTyped(json, false);
}

export function SwarmResponseDecompositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwarmResponseDecomposition {
    if (json == null) {
        return json;
    }
    return {
        
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
        'subtaskCount': json['subtaskCount'] == null ? undefined : json['subtaskCount'],
    };
}

  export function SwarmResponseDecompositionToJSON(json: any): SwarmResponseDecomposition {
      return SwarmResponseDecompositionToJSONTyped(json, false);
  }

  export function SwarmResponseDecompositionToJSONTyped(value?: SwarmResponseDecomposition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reasoning': value['reasoning'],
        'subtaskCount': value['subtaskCount'],
    };
}

