/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface UploadImageClassify200Response
 */
export interface UploadImageClassify200Response {
    /**
     * Model's description of the image
     * @type {string}
     * @memberof UploadImageClassify200Response
     */
    result?: string;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadImageClassify200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadImageClassify200Response interface.
 */
export function instanceOfUploadImageClassify200Response(value: object): value is UploadImageClassify200Response {
    return true;
}

export function UploadImageClassify200ResponseFromJSON(json: any): UploadImageClassify200Response {
    return UploadImageClassify200ResponseFromJSONTyped(json, false);
}

export function UploadImageClassify200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageClassify200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadImageClassify200ResponseToJSON(json: any): UploadImageClassify200Response {
      return UploadImageClassify200ResponseToJSONTyped(json, false);
  }

  export function UploadImageClassify200ResponseToJSONTyped(value?: UploadImageClassify200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

