/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface UploadReadPdf200Response
 */
export interface UploadReadPdf200Response {
    /**
     * Full extracted text
     * @type {string}
     * @memberof UploadReadPdf200Response
     */
    text?: string;
    /**
     * Total number of pages in the PDF
     * @type {number}
     * @memberof UploadReadPdf200Response
     */
    pages?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof UploadReadPdf200Response
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the UploadReadPdf200Response interface.
 */
export function instanceOfUploadReadPdf200Response(value: object): value is UploadReadPdf200Response {
    return true;
}

export function UploadReadPdf200ResponseFromJSON(json: any): UploadReadPdf200Response {
    return UploadReadPdf200ResponseFromJSONTyped(json, false);
}

export function UploadReadPdf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadReadPdf200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function UploadReadPdf200ResponseToJSON(json: any): UploadReadPdf200Response {
      return UploadReadPdf200ResponseToJSONTyped(json, false);
  }

  export function UploadReadPdf200ResponseToJSONTyped(value?: UploadReadPdf200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'pages': value['pages'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

