/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepDefinition } from './StepDefinition';
import {
    StepDefinitionFromJSON,
    StepDefinitionFromJSONTyped,
    StepDefinitionToJSON,
    StepDefinitionToJSONTyped,
} from './StepDefinition';

/**
 * 
 * @export
 * @interface WorkflowRequest
 */
export interface WorkflowRequest {
    /**
     * Ordered list of workflow step definitions.
     * 
     * @type {Array<StepDefinition>}
     * @memberof WorkflowRequest
     */
    steps: Array<StepDefinition>;
    /**
     * When `true`, unlocks `write_file`, `scaffold_project`, and `document_ingest`
     * tools for all steps.
     * 
     * @type {boolean}
     * @memberof WorkflowRequest
     */
    allowWrite?: boolean;
    /**
     * Force a specific model profile for all steps, bypassing automatic routing.
     * 
     * @type {string}
     * @memberof WorkflowRequest
     */
    profile?: WorkflowRequestProfileEnum;
    /**
     * How prior step outputs are carried into subsequent steps.
     * `none` = isolated; `summary` = compact bullet summary (default);
     * `full` = verbatim full output.
     * 
     * @type {string}
     * @memberof WorkflowRequest
     */
    carry?: WorkflowRequestCarryEnum;
    /**
     * Per-step agent-loop iteration cap.  Overrides `AGENTS_MAX_STEPS` for this
     * request only.  Defaults to `AGENTS_MAX_STEPS` (env var, default 5).
     * 
     * @type {number}
     * @memberof WorkflowRequest
     */
    maxStepsPerStep?: number;
}


/**
 * @export
 */
export const WorkflowRequestProfileEnum = {
    Fast: 'fast',
    Reasoning: 'reasoning',
    Code: 'code',
    Default: 'default'
} as const;
export type WorkflowRequestProfileEnum = typeof WorkflowRequestProfileEnum[keyof typeof WorkflowRequestProfileEnum];

/**
 * @export
 */
export const WorkflowRequestCarryEnum = {
    None: 'none',
    Summary: 'summary',
    Full: 'full'
} as const;
export type WorkflowRequestCarryEnum = typeof WorkflowRequestCarryEnum[keyof typeof WorkflowRequestCarryEnum];


/**
 * Check if a given object implements the WorkflowRequest interface.
 */
export function instanceOfWorkflowRequest(value: object): value is WorkflowRequest {
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function WorkflowRequestFromJSON(json: any): WorkflowRequest {
    return WorkflowRequestFromJSONTyped(json, false);
}

export function WorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': ((json['steps'] as Array<any>).map(StepDefinitionFromJSON)),
        'allowWrite': json['allowWrite'] == null ? undefined : json['allowWrite'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'carry': json['carry'] == null ? undefined : json['carry'],
        'maxStepsPerStep': json['maxStepsPerStep'] == null ? undefined : json['maxStepsPerStep'],
    };
}

  export function WorkflowRequestToJSON(json: any): WorkflowRequest {
      return WorkflowRequestToJSONTyped(json, false);
  }

  export function WorkflowRequestToJSONTyped(value?: WorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': ((value['steps'] as Array<any>).map(StepDefinitionToJSON)),
        'allowWrite': value['allowWrite'],
        'profile': value['profile'],
        'carry': value['carry'],
        'maxStepsPerStep': value['maxStepsPerStep'],
    };
}

