/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowStepResult
 */
export interface WorkflowStepResult {
    /**
     * Zero-based position of this step in the workflow.
     * @type {number}
     * @memberof WorkflowStepResult
     */
    index?: number;
    /**
     * The original task string for this step.
     * @type {string}
     * @memberof WorkflowStepResult
     */
    task?: string;
    /**
     * The agent's final answer for this step.
     * @type {string}
     * @memberof WorkflowStepResult
     */
    result?: string;
    /**
     * Whether this step completed without throwing.
     * @type {boolean}
     * @memberof WorkflowStepResult
     */
    success?: boolean;
    /**
     * Wall-clock execution time for this step in milliseconds.
     * @type {number}
     * @memberof WorkflowStepResult
     */
    durationMs?: number;
    /**
     * Error message (only present when `success` is `false`).
     * @type {string}
     * @memberof WorkflowStepResult
     */
    error?: string;
}

/**
 * Check if a given object implements the WorkflowStepResult interface.
 */
export function instanceOfWorkflowStepResult(value: object): value is WorkflowStepResult {
    return true;
}

export function WorkflowStepResultFromJSON(json: any): WorkflowStepResult {
    return WorkflowStepResultFromJSONTyped(json, false);
}

export function WorkflowStepResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepResult {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'task': json['task'] == null ? undefined : json['task'],
        'result': json['result'] == null ? undefined : json['result'],
        'success': json['success'] == null ? undefined : json['success'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function WorkflowStepResultToJSON(json: any): WorkflowStepResult {
      return WorkflowStepResultToJSONTyped(json, false);
  }

  export function WorkflowStepResultToJSONTyped(value?: WorkflowStepResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'task': value['task'],
        'result': value['result'],
        'success': value['success'],
        'durationMs': value['durationMs'],
        'error': value['error'],
    };
}

