/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { WorkflowStepResult } from './WorkflowStepResult';
import {
    WorkflowStepResultFromJSON,
    WorkflowStepResultFromJSONTyped,
    WorkflowStepResultToJSON,
    WorkflowStepResultToJSONTyped,
} from './WorkflowStepResult';

/**
 * 
 * @export
 * @interface WorkflowResponse
 */
export interface WorkflowResponse {
    /**
     * Per-step results in execution order.
     * @type {Array<WorkflowStepResult>}
     * @memberof WorkflowResponse
     */
    steps?: Array<WorkflowStepResult>;
    /**
     * `true` when every step completed successfully.
     * @type {boolean}
     * @memberof WorkflowResponse
     */
    allSucceeded?: boolean;
    /**
     * Total wall-clock duration across all steps in milliseconds.
     * @type {number}
     * @memberof WorkflowResponse
     */
    totalDurationMs?: number;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof WorkflowResponse
     */
    meta?: ResponseMeta;
}

/**
 * Check if a given object implements the WorkflowResponse interface.
 */
export function instanceOfWorkflowResponse(value: object): value is WorkflowResponse {
    return true;
}

export function WorkflowResponseFromJSON(json: any): WorkflowResponse {
    return WorkflowResponseFromJSONTyped(json, false);
}

export function WorkflowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(WorkflowStepResultFromJSON)),
        'allSucceeded': json['allSucceeded'] == null ? undefined : json['allSucceeded'],
        'totalDurationMs': json['totalDurationMs'] == null ? undefined : json['totalDurationMs'],
        'meta': json['meta'] == null ? undefined : ResponseMetaFromJSON(json['meta']),
    };
}

  export function WorkflowResponseToJSON(json: any): WorkflowResponse {
      return WorkflowResponseToJSONTyped(json, false);
  }

  export function WorkflowResponseToJSONTyped(value?: WorkflowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(WorkflowStepResultToJSON)),
        'allSucceeded': value['allSucceeded'],
        'totalDurationMs': value['totalDurationMs'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

